apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}
spec:
  type: {{ .Values.container.type }}
  selector:
    app: {{ .Values.container.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.container.targetPort }}
