jobs:
  shared_job:
    # Импортирование повторно используемого workflow из вашего репозитория и ветки
    uses: aslan-ali/Shared-Pipelines/.github/workflows/blank.yml@main
    with:
      node-version: '18.1'
